### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by alkoclick** [siculo/sbt-bom#9]
Hey @siculo , this project doesn't have a license which makes it impossible for use by other open source developers. Would you be interested in adding a basic license, such as MIT so that others can contribute to this repo or its forks?

For more context, see [this SO question](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) and the [Github guidelines](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

**Comment by siculo** [comment]
Ok, I added MIT license to project.
